---
title: "Matrix Allergy_CEA"
format: html
editor: visual
---


```{r}
library(tidyverse)
library(heemod)
library(diagram)
library(ggplot2)
```

Develop parameter
```{r}
# import the Canada 2020 life table with mortality value in all ages (both sex)

life_table<-read.csv('./life_table_CAN_2020.csv')

# remove row 111 from life_table (age older than 111 )

life_table <- life_table %>% 
                filter(Age.group != "110 years and over") %>% 
                separate(Age.group, into = c("Age", "Unit"), sep = " ") %>% 
                select(Age, VALUE) %>% 
                mutate(Age=as.numeric(Age), fatality_daily = rescale_prob(p = VALUE, from = 365 ))


# build age parameter,

par_allerg <-define_parameters(
                  age_initial = 1,
                  age = floor(age_initial + model_time/365)
)

# age-dependent remission probability

ar_age<-function(age) {
  if_else(age <=6, rescale_prob(0.058,from = 365), 0) 
}

#_ww: watch and wait scenario
#_ED: transfer to ED scenario 
#ns: non severe
#sw: severe watch and wait,
#sED: severe transfer to ED,
#sh: severe with hospitalized, 
#ar: food allergy remission, 
#faf: food allergy fatality,
#dr: discount rate
#acm: all-cause 

# parameter for X10 mortality in watch and wait 

#parameter for transition 
par_allerg<-modify(
par_allerg,
p_severe    = 0.087,
p_ns_ar     = ar_age(age = age),                                     # transition from non-severe reaction to food allergy remission
p_ns_sw_ww  = (1-0.14) * rescale_prob(p =p_severe, from = 365) ,     # non-severe reaction to severe reaction for watch and wait
p_ns_sED_ww = 0.14 * rescale_prob(p = p_severe, from = 365),         # non-severe reaction to severe reaction transfer to ED for watch and wait
p_sh_ED      = 0.001684833,                                          # transition from severe state ED to hospitalization 
p_sh_ww      = 0.0193168,                                            # transition from severe state watch & wait to hospitalization
p_ns_sED_ED = rescale_prob(p =p_severe, from = 365),                 # transition from non-severe to ED
p_sh_faf    = 0.0045,                                                # transition from hospitalization to food allergy fatality
acm         = look_up(data = life_table, Age = age,                  #daily all-cause mortality
                      value = "fatality_daily"),
p_ww_faf    = 8.692562e-05,                                          #transition from watch and wait to food allergy fatality 
dr          = rescale_prob( p=0.015, from = 365),                    #discount rate
)

# parameter for cost and utility
par_allerg<-modify(
par_allerg,
treatment_cost_ED          = 0.8 +51.3,                            # epi treatment cost in ED 
treatment_cost_ww          = 95,                                   # EAI treatment cost in watch and wait 
treatment_cost_ww_ED       = 0.8,                                  # epi cost for ED transfer in watch and wait scenario 
remission_cost_all         = 513/365,                              # remission patient daily cost for all scenario
medical_cost_ns            = 1254/365,                             # daily medical cost for Canadian with food allergy
ambulance_cost_ED_ED       = 848,                                  # ambulance cost 
medical_cost_ED_ED         = 331,                                  # daily medical cost in ED 
medical_cost_hospital      = 1866,                                 # medical cost hospitalized
indirect_cost_allergy      = 8413/365,                             # indirect cost for food allergy-societal
out_of_pocket_cost_allergy = 2251/365,                             # out of pocket cost for food allergy-societal 
indirect_cost_hospital      = 251,                                 # indirect cost in hospitalization - societal 
out_of_pocket_emergency     = 97,                                  # out of pocket in ED-societal 
indirect_cost_emergency     = 113,                                 # indirect cost in ED -societal 
utility_far                = 0.93/365,                             # utility -food allergy remission 
utility_fa                 = 0.92/365,                             # utility- food allergy non-severe
utility_sr                 = 0.83/365,                             # utility-severe reaction 

)
```

Develop strategy

```{r}
# transition matrix for ED transfer-same for both strategy 

Transition_ED <- define_transition(
  state_names = c("state_ar","state_ns", "state_sw", "state_sED", "state_sh", "state_faf","state_acm"),
  C,            0,      0,          0,           0,         0,           acm,
  p_ns_ar,      C,      0,          p_ns_sED_ED, 0,         0,           acm,
  0,            0,      0,          0,           0,         1,           0,
  0,            C,      0,          0,           p_sh_ED,   0,           acm,
  0,            C,      0,          0,           0,         p_sh_faf,    acm,
  0,            0,      0,          0,           0,         1,           0,
  0,            0,      0,          0,           0,         0,           1
)

#transition matrix for watch and wait -patient will get hospitalized after watch and wait state
Transition_watch <- define_transition(
  state_names = c("state_ar","state_ns", "state_sw", "state_sED", "state_sh", "state_faf","state_acm"),
  C,            0,      0,          0,           0,           0,           acm,
  p_ns_ar,      C,      p_ns_sw_ww, p_ns_sED_ww, 0,           0,           acm,
  0,            C,      0,          0,           p_sh_ww,     0,           acm,
  0,            C,      0,          0,           p_sh_ED,     0,           acm,
  0,            C,      0,          0,           0,           p_sh_faf,    acm,
  0,            0,      0,          0,           0,           1,           0,
  0,            0,      0,          0,           0,           0,           1
)  

#transition matrix for watch and wait -patient will not get hospitalized after watch and wait state
Transition_watch_no_hs <- define_transition(
  state_names = c("state_ar","state_ns", "state_sw", "state_sED", "state_sh", "state_faf","state_acm"),
  C,            0,      0,          0,           0,           0,           acm,
  p_ns_ar,      C,      p_ns_sw_ww, p_ns_sED_ww, 0,           0,           acm,
  0,            C,      0,          0,           0,           p_ww_faf,    acm,
  0,            C,      0,          0,           p_sh_ED,     0,           acm,
  0,            C,      0,          0,           0,           p_sh_faf,    acm,
  0,            0,      0,          0,           0,           1,           0,
  0,            0,      0,          0,           0,           0,           1
)

```

Define cost and utility 
```{r}
# food allergy remission 

state_ar<-define_state(
  remission_cost            = remission_cost_all ,
  medical_cost              = 0,
  treatment_cost            = 0,
  ambulance_cost            = 0,
  medical_cost_ED           = 0,
  medical_cost_hospitalized = 0,
  utility                   = utility_far,
  cost_total                = discount(remission_cost, r=dr),
  utility_total             = discount(utility, r=dr)
)

# non-severe reaction

state_ns<-define_state(
  remission_cost            = 0,
  medical_cost              = medical_cost_ns,
  treatment_cost            = 0,
  ambulance_cost            = 0,
  medical_cost_ED           = 0,
  medical_cost_hospitalized = 0,
  utility                   = utility_fa,
  cost_total                = discount(medical_cost, r=dr),
  utility_total             = discount(utility, r=dr)
)

#severe allergic reaction-watch and waiting 

state_sw<-define_state(
  remission_cost            = 0,
  medical_cost              = medical_cost_ns,
  treatment_cost            = treatment_cost_ww,
  ambulance_cost            = 0,
  medical_cost_ED           = 0,
  medical_cost_hospitalized = 0,
  utility                   = utility_sr,
  cost_total                = discount(medical_cost+treatment_cost, r=dr),
  utility_total             = discount(utility, r=dr)
)

#severe allergic reaction - ED transfer 

state_sED<- define_state(
  remission_cost            = 0,
  medical_cost              = medical_cost_ns, 
  treatment_cost            = dispatch_strategy(
                              ED_transfer = treatment_cost_ED,
                              watch_wait  = treatment_cost_ww_ED),
  ambulance_cost            = ambulance_cost_ED_ED,
  medical_cost_ED           = medical_cost_ED_ED,
  medical_cost_hospitalized = 0,
  utility                   = utility_sr,
  cost_total                = discount(medical_cost + treatment_cost + ambulance_cost + medical_cost_ED , r=dr),
  utility_total             = discount(utility, r=dr)
)

#severe allergic reaction -hospitalized 

state_sh<-define_state(
  remission_cost            = 0,
  medical_cost              = 0,
  treatment_cost            = 0,
  ambulance_cost            = 0,
  medical_cost_ED           = 0,
  medical_cost_hospitalized = medical_cost_hospital,
  utility                   = utility_sr,
  cost_total                = discount(medical_cost_hospitalized,r=dr),
  utility_total             = discount(utility, r=dr)
)


#food allergy fatality
state_faf<-define_state(
  remission_cost            = 0,
  medical_cost              = 0, 
  medical_cost_hospitalized = 0,
  treatment_cost            = 0,
  ambulance_cost            = 0,
  medical_cost_ED           = 0,
  utility                   = 0,
  cost_total                = 0,
  utility_total             = 0
)

#all-cause mortality
state_acm<-define_state(
  remission_cost            = 0,
  medical_cost              = 0, 
  medical_cost_hospitalized = 0,
  treatment_cost            = 0,
  ambulance_cost            = 0,
  medical_cost_ED           = 0,
  utility                   = 0,
  cost_total                = 0,
  utility_total             = 0
)

```

Define straty and initial 

```{r}
#strategy for ED -same for both matrix 
strategy_ED<-define_strategy(
  transition  = Transition_ED,
  state_ar    = state_ar,
  state_ns    = state_ns,
  state_sw    = state_sw,
  state_sED   = state_sED,
  state_sh    = state_sh,
  state_faf   = state_faf,
  state_acm   = state_acm
)

#strategy for watch & wait -patient will get hospitalized after watch and wait state
strategy_watch<- define_strategy(
  transition  = Transition_watch,
  state_ar    = state_ar,
  state_ns    = state_ns,
  state_sw    = state_sw,
  state_sED   = state_sED,
  state_sh    = state_sh,
  state_faf   = state_faf,
  state_acm   = state_acm
)

#strategy for watch and wait not -patient will not get hospitalized after watch and wait state
strategy_watch_no_hs<- define_strategy(
  transition  = Transition_watch_no_hs,
  state_ar    = state_ar,
  state_ns    = state_ns,
  state_sw    = state_sw,
  state_sED   = state_sED,
  state_sh    = state_sh,
  state_faf   = state_faf,
  state_acm   = state_acm
)

time0 <- define_init(state_ar  = 0,
                     state_ns  = 10000,
                     state_sw  = 0,
                     state_sED = 0,
                     state_sh  = 0,
                     state_faf = 0,
                     state_acm = 0)
```

run model -patient will get hospitalized after watch and wait state
```{r}
# patient will not get hospitalized after watch and wait state
allergy_mod_10<-run_model(
  parameters  = par_allerg,
  ED_transfer = strategy_ED,
  watch_wait  = strategy_watch,
  init        = time0,
  cycles      = 7300,
  cost        = cost_total,
  effect      = utility_total,
  method = "beginning"
)

summary(allergy_mod_10)
mod_10_count <-get_counts(allergy_mod_10)

mod_10_count %>%   
  group_by(.strategy_names, state_names) %>% 
  summarize(avg=mean(count), sum=sum(count))

```

run model -patient will NOT get hospitalized after watch and wait state 
```{r}
allergy_mod_10_no_hs<-run_model(
  parameters  = par_allerg,
  ED_transfer = strategy_ED,
  watch_wait  = strategy_watch_no_hs,
  init        = time0,
  cycles      = 7300,
  cost        = cost_total,
  effect      = utility_total,
  method = "beginning"
)
summary(allergy_mod_10_no_hs)
mod_10_count_no_hs <-get_counts(allergy_mod_10_no_hs)

mod_10_count_no_hs %>%   
  group_by(.strategy_names, state_names) %>% 
  summarize(avg=mean(count), sum=sum(count))
```